#!/usr/bin/env python3
"""_fs_filters.py — single source of truth for first-party file/dir filters.

Leaf module: stdlib-only, no imports from sibling scripts. Shared by the two
directory WALKERS in this skill (audit_hotspots.py, coverage_ledger.py) so a fix
to what counts as first-party source lands once instead of drifting across
scanners. Migrated from audit_hotspots.py (contest-refactor avalanche plan,
Phase 0) after a live BenchHype run showed coverage_ledger's own copy of these
filters (imported from audit_boundaries.py) let `.artifacts/DerivedData/**` and
`Tests/**/StarterSoundFixtures.swift` into its citation-coverage denominator.

`audit_boundaries.py` deliberately does NOT re-export these names: its own
IGNORE_DIRS/_is_test_file/_is_generated_file are read directly by
audit_suppressions.py and diverge from this module in ways that matter (fewer
ignored dirs, Python-only test-file suffixes, a `_pb2.py` generated-file check
with no equivalent here) — see the comment above `IGNORE_DIRS` in that file.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

# Directory names never scanned: VCS/build/cache/vendor + test + generated trees.
# Matched case-insensitively, EXCEPT _EXACT_CASE_IGNORE_DIRS below.
IGNORE_DIRS = frozenset(
    {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        ".env",
        "build",
        "dist",
        ".tox",
        ".mypy_cache",
        ".pytest_cache",
        "site-packages",
        "tests",
        "test",
        ".eggs",
        ".build",
        "deriveddata",
        "target",
        ".gradle",
        "bin",
        "obj",
        "vendor",
    }
)

# Matched exact-case only: Django-style generated migration trees are always
# lowercase `migrations/` by convention, but capitalized `Migrations/` in
# Swift/Kotlin persistence code is hand-written source, not generated (observed
# casualty: BenchHypeKit Sources/BenchHypePersistence/Migrations/LocalURLMigrationV1.swift).
_EXACT_CASE_IGNORE_DIRS = frozenset({"migrations"})

_GENERATED_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "Generated by",
    "AUTOGENERATED",
    "code generated by",
)


def is_ignored_path(parts: Sequence[str]) -> bool:
    """True if any component of a path lands in an excluded tree.

    `parts` must be relative to the scan root (e.g. `Path(...).relative_to(root).parts`)
    -- passing absolute-path parts risks matching an ANCESTOR directory outside the
    repo (a checkout under a path segment literally named "build" or ".cache").
    """
    parts = tuple(parts)
    for part in parts:
        if part.lower() in IGNORE_DIRS or part in _EXACT_CASE_IGNORE_DIRS:
            return True
    # ponytail: hidden dirs are tooling/build state by convention (.artifacts,
    # .swiftpm, .contest-refactor); deliberately-hidden source would need a
    # carve-out here. The last element is the filename, exempt from this check --
    # a source file that merely starts with "." is not a hidden directory.
    return any(part.startswith(".") for part in parts[:-1])


def is_test_file(name: str) -> bool:
    lower = name.lower()
    return lower.startswith("test_") or lower.endswith(
        (
            "_test.py",
            "_test.go",
            "_test.rs",
            "tests.swift",
            "test.swift",
            "spec.swift",
            ".test.ts",
            ".spec.ts",
            ".test.tsx",
            ".spec.tsx",
            ".test.js",
            ".spec.js",
            "test.kt",
            "tests.kt",
            "test.java",
            "tests.java",
        )
    )


def is_generated_file(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8", errors="ignore") as source:
            head = source.read(1024)
        return any(marker.lower() in head.lower() for marker in _GENERATED_MARKERS)
    except OSError:
        return False


def normalize_roots(roots: list[str]) -> list[str]:
    """Sort, dedupe, posix-separated, no trailing slash. Pure -- no filesystem access."""
    seen = {r.replace("\\", "/").rstrip("/") for r in roots}
    seen.discard("")
    return sorted(seen)
