#!/usr/bin/env python3
# WAIVER: module-size — standalone multi-language hotspot candidate scanner
#   (Python stdlib AST + ast-grep multi-language engine + Queue A/B/C cognitive
#   reasoning signal extractors + JSON epistemic reporter). Self-contained single-file
#   CLI helper for Step 6 candidate evidence.
"""audit_hotspots.py — candidate-evidence detector for implementation hotspots.

Mechanical helper for Method Step 6 (Review simplification & clarity).
Identifies functions and methods exhibiting high cognitive reasoning burden across
three independent candidate queues:
  - Queue A: Control Reasoning Density (decisions, nesting, complex condition operands)
  - Queue B: Temporal Mutation & State Reasoning (mutation span, reassignments across branches)
  - Queue C: Private Navigation Fragmentation (single-use private helpers, helper call depth)

EPISTEMIC CONTRACT (Meta-Rule 1):
  Output is CANDIDATE EVIDENCE for the Critic (promotion_allowed: false).
  Metrics support judgment; they never decide it.
  The Critic independently inspects the symbol and its immediate private neighborhood,
  deriving any findings strictly from source semantics (Claim → Source → Consequence → Remedy).
  No metric score or threshold may appear in findings, severity ratings, or scorecards.

Supported stacks:
  - Python (via stdlib ast)
  - Swift (function and signal nodes via open-source ast-grep)
  - TypeScript, JavaScript, Go, Rust, Kotlin, Java (ast-grep boundaries + masked heuristics)
  If ast-grep is not installed on non-Python repositories, multi-language scanning
  is skipped gracefully with installation instructions.

Usage:
  scripts/audit_hotspots.py [<repo-root>] [--top-k N] [--json]

Exit codes:
  0 = reported `ok`, `partial`, `absent`, or `not_applicable`
  2 = usage error (bad path or arguments)
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path

from audit_clones import _mask as _mask_source

# Directory names never scanned: VCS/build/cache/vendor + test + generated trees.
IGNORE_DIRS = frozenset(
    {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        ".env",
        "build",
        "dist",
        ".tox",
        ".mypy_cache",
        ".pytest_cache",
        "site-packages",
        "migrations",
        "tests",
        "test",
        ".eggs",
        ".build",
        "DerivedData",
        "target",
        ".gradle",
        "bin",
        "obj",
        "vendor",
    }
)

_GENERATED_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "Generated by",
    "AUTOGENERATED",
    "code generated by",
)

_LANG_BY_EXT: dict[str, str] = {
    ".py": "python",
    ".swift": "swift",
    ".ts": "ts",
    ".tsx": "tsx",
    ".js": "js",
    ".jsx": "js",
    ".mjs": "js",
    ".cjs": "js",
    ".go": "go",
    ".rs": "rust",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".java": "java",
}

AST_GREP_KINDS: dict[str, list[str]] = {
    "swift": ["function_declaration"],
    "ts": ["function_declaration", "method_definition", "arrow_function"],
    "tsx": ["function_declaration", "method_definition", "arrow_function"],
    "js": ["function_declaration", "method_definition", "arrow_function"],
    "go": ["function_declaration", "method_declaration"],
    "rust": ["function_item"],
    "kotlin": ["function_declaration"],
    "java": ["method_declaration", "constructor_declaration"],
}

_SWIFT_NODE_SELECTOR = (
    ":is(class_declaration, if_statement, guard_statement, for_statement, "
    "while_statement, catch_block, switch_statement, switch_entry, assignment, "
    "property_declaration, call_expression, conjunction_expression, disjunction_expression)"
)

INSTALL_INSTRUCTIONS = (
    "brew install ast-grep (macOS/Homebrew) | "
    "cargo install ast-grep-cli (Rust/Cargo) | "
    "npm install -g @ast-grep/cli (Node/NPM)"
)


def _force_utf8_stdout() -> None:
    """Emit UTF-8 regardless of console code page."""
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")


def _is_test_file(name: str) -> bool:
    lower = name.lower()
    return lower.startswith("test_") or lower.endswith(
        (
            "_test.py",
            "_test.go",
            "_test.rs",
            "tests.swift",
            "test.swift",
            "spec.swift",
            ".test.ts",
            ".spec.ts",
            ".test.tsx",
            ".spec.tsx",
            ".test.js",
            ".spec.js",
            "test.kt",
            "tests.kt",
            "test.java",
            "tests.java",
        )
    )


def _is_generated_file(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8", errors="ignore") as source:
            head = source.read(1024)
        return any(marker.lower() in head.lower() for marker in _GENERATED_MARKERS)
    except OSError:
        return False


@dataclass
class FunctionSignals:
    decision_count: int = 0
    max_nesting: int = 0
    condition_operand_max: int = 0
    logical_lines: int = 0

    mutation_sites: int = 0
    mutation_span: int = 0
    distinct_mutated_fields: int = 0
    mutable_local_count: int = 0

    private_helper_fanout: int = 0
    single_use_private_helper_count: int = 0
    private_call_depth: int = 0
    direct_call_fanout: int = 0


@dataclass
class CandidateSymbol:
    path: str
    symbol: str
    start_line: int
    end_line: int
    signals: FunctionSignals
    candidate_queues: list[str] = field(default_factory=list)
    primary_queue: str = ""
    direct_private_helpers: list[str] = field(default_factory=list)

    @property
    def control_score(self) -> int:
        return (
            self.signals.decision_count * 3
            + self.signals.max_nesting * 4
            + self.signals.condition_operand_max * 2
            + (self.signals.logical_lines // 10)
        )

    @property
    def mutation_score(self) -> int:
        return (
            self.signals.mutation_span * 2
            + self.signals.mutation_sites * 3
            + self.signals.distinct_mutated_fields * 2
            + self.signals.mutable_local_count * 4
        )

    @property
    def navigation_score(self) -> int:
        return (
            self.signals.single_use_private_helper_count * 20
            + self.signals.private_helper_fanout * 5
            + self.signals.private_call_depth * 8
            + self.signals.direct_call_fanout
        )


@dataclass
class _ScannedFunction:
    candidate: CandidateSymbol
    owner: str
    name: str
    direct_calls: list[str]
    is_private: bool


class _PythonFunctionASTAnalyzer(ast.NodeVisitor):
    """Analyzes a single Python FunctionDef / AsyncFunctionDef AST node."""

    def __init__(
        self, fn_node: ast.FunctionDef | ast.AsyncFunctionDef, source_lines: list[str]
    ) -> None:
        self.fn_node = fn_node
        self.source_lines = source_lines
        self.signals = FunctionSignals()
        self.called_functions: set[str] = set()
        self.called_private_helpers: set[str] = set()

        self.var_assignments: dict[str, list[int]] = defaultdict(list)
        self.var_reads: dict[str, list[int]] = defaultdict(list)

    def analyze(self) -> FunctionSignals:
        start = self.fn_node.lineno - 1
        end = getattr(self.fn_node, "end_lineno", self.fn_node.lineno)
        body_lines = self.source_lines[start:end]
        self.signals.logical_lines = sum(
            1 for line in body_lines if line.strip() and not line.strip().startswith("#")
        )

        self._walk_body(self.fn_node.body, depth=0)
        self._compute_mutation_signals()

        self.signals.direct_call_fanout = len(self.called_functions)
        self.signals.private_helper_fanout = len(self.called_private_helpers)
        return self.signals

    def _walk_body(self, nodes: list[ast.stmt], depth: int) -> None:
        for node in nodes:
            self._process_stmt(node, depth)

    def _process_stmt(self, node: ast.AST, depth: int) -> None:
        if depth > self.signals.max_nesting:
            self.signals.max_nesting = depth

        if isinstance(node, ast.If):
            self.signals.decision_count += 1
            self._analyze_condition(node.test)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                    self._process_stmt(node.orelse[0], depth)
                else:
                    self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, (ast.For, ast.AsyncFor)):
            self.signals.decision_count += 1
            self._extract_assign_targets(node.target, node.lineno)
            self.visit(node.iter)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, ast.While):
            self.signals.decision_count += 1
            self._analyze_condition(node.test)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, (ast.Try, getattr(ast, "TryStar", ast.Try))):
            self._walk_body(node.body, depth + 1)
            for handler in node.handlers:
                self.signals.decision_count += 1
                if handler.name:
                    self.var_assignments[handler.name].append(handler.lineno)
                self._walk_body(handler.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)
            if node.finalbody:
                self._walk_body(node.finalbody, depth + 1)

        elif isinstance(node, (ast.With, ast.AsyncWith)):
            for item in node.items:
                if item.optional_vars:
                    self._extract_assign_targets(item.optional_vars, node.lineno)
                self.visit(item.context_expr)
            self._walk_body(node.body, depth + 1)

        elif isinstance(node, getattr(ast, "Match", ())):  # Python 3.10+
            self.visit(node.subject)
            for case in node.cases:
                self.signals.decision_count += 1
                if case.guard:
                    self._analyze_condition(case.guard)
                self._walk_body(case.body, depth + 1)

        elif isinstance(node, ast.Assign):
            for target in node.targets:
                self._extract_assign_targets(target, node.lineno)
            self.visit(node.value)

        elif isinstance(node, ast.AugAssign):
            self._extract_assign_targets(node.target, node.lineno)
            self.visit(node.value)

        elif isinstance(node, ast.AnnAssign):
            self._extract_assign_targets(node.target, node.lineno)
            if node.value:
                self.visit(node.value)

        else:
            self.visit(node)

    def _analyze_condition(self, expr: ast.AST) -> None:
        self._record_condition_complexity(expr)
        self.visit(expr)

    def _record_condition_complexity(self, expr: ast.AST) -> None:
        count = 1
        for sub in ast.walk(expr):
            if isinstance(sub, ast.BoolOp):
                count += len(sub.values) - 1
                self.signals.decision_count += len(sub.values) - 1
            elif isinstance(sub, ast.Compare):
                count += len(sub.ops) - 1
        if count > self.signals.condition_operand_max:
            self.signals.condition_operand_max = count

    def _extract_assign_targets(self, target: ast.AST, lineno: int) -> None:
        if isinstance(target, ast.Name):
            self.var_assignments[target.id].append(lineno)
        elif isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name):
            if target.value.id == "self":
                self.var_assignments[f"self.{target.attr}"].append(lineno)
        elif isinstance(target, (ast.Tuple, ast.List)):
            for elt in target.elts:
                self._extract_assign_targets(elt, lineno)

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load):
            self.var_reads[node.id].append(node.lineno)
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if (
            isinstance(node.ctx, ast.Load)
            and isinstance(node.value, ast.Name)
            and node.value.id == "self"
        ):
            self.var_reads[f"self.{node.attr}"].append(node.lineno)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        fn_name = ""
        is_private = False
        if isinstance(node.func, ast.Name):
            fn_name = node.func.id
            if fn_name.startswith("_") and not fn_name.startswith("__"):
                is_private = True
        elif isinstance(node.func, ast.Attribute):
            fn_name = node.func.attr
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id == "self"
                and fn_name.startswith("_")
                and not fn_name.startswith("__")
            ):
                is_private = True

        if fn_name:
            self.called_functions.add(fn_name)
            if is_private:
                self.called_private_helpers.add(fn_name)

        self.generic_visit(node)

    def visit_IfExp(self, node: ast.IfExp) -> None:
        self.signals.decision_count += 1
        self._record_condition_complexity(node.test)
        self.generic_visit(node)

    def _visit_comprehension(self, node: ast.AST) -> None:
        generators = getattr(node, "generators", [])
        self.signals.decision_count += sum(1 + len(generator.ifs) for generator in generators)
        self.generic_visit(node)

    visit_ListComp = _visit_comprehension
    visit_SetComp = _visit_comprehension
    visit_DictComp = _visit_comprehension
    visit_GeneratorExp = _visit_comprehension

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        del node

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        del node

    def visit_Lambda(self, node: ast.Lambda) -> None:
        del node

    def _compute_mutation_signals(self) -> None:
        mutated_vars = {k: v for k, v in self.var_assignments.items() if len(v) >= 2}
        self.signals.mutable_local_count = len(mutated_vars)
        self.signals.distinct_mutated_fields = len(
            [k for k, v in self.var_assignments.items() if len(v) >= 2 or k.startswith("self.")]
        )
        self.signals.mutation_sites = sum(
            len(v) - 1 for v in self.var_assignments.values() if len(v) >= 2
        )

        max_span = 0
        for var_name, assign_lines in self.var_assignments.items():
            if len(assign_lines) >= 2 or (var_name.startswith("self.") and assign_lines):
                first_assign = assign_lines[0]
                reads = self.var_reads.get(var_name, [])
                all_accesses = assign_lines + reads
                last_access = max(all_accesses) if all_accesses else first_assign
                span = last_access - first_assign
                if span > max_span:
                    max_span = span

        self.signals.mutation_span = max_span


def scan_python_file(path: Path, repo_root: Path) -> tuple[list[CandidateSymbol], bool]:
    """Scans a single Python file for function & method candidate symbols."""
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, OSError, UnicodeDecodeError):
        return [], False

    source_lines = source.splitlines()
    rel_path = str(path.relative_to(repo_root))

    candidates: list[CandidateSymbol] = []
    helper_call_map: dict[str, set[tuple[str, int]]] = defaultdict(set)
    private_helper_defs: dict[str, ast.FunctionDef | ast.AsyncFunctionDef] = {}
    helper_keys_by_candidate: dict[tuple[str, int], list[str]] = {}

    def extract_from_scope(nodes: list[ast.stmt], prefix: str = "", is_class: bool = False) -> None:
        for node in nodes:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                symbol_name = f"{prefix}.{node.name}" if prefix else node.name
                analyzer = _PythonFunctionASTAnalyzer(node, source_lines)
                signals = analyzer.analyze()

                candidate = CandidateSymbol(
                    path=rel_path,
                    symbol=symbol_name,
                    start_line=node.lineno,
                    end_line=getattr(node, "end_lineno", node.lineno),
                    signals=signals,
                    direct_private_helpers=sorted(analyzer.called_private_helpers),
                )
                candidates.append(candidate)
                candidate_key = (symbol_name, node.lineno)
                helper_keys = [
                    f"{prefix}.{helper}" if is_class else helper
                    for helper in analyzer.called_private_helpers
                ]
                helper_keys_by_candidate[candidate_key] = helper_keys

                if node.name.startswith("_") and not node.name.startswith("__"):
                    private_helper_defs[symbol_name] = node

                for helper_key in helper_keys:
                    helper_call_map[helper_key].add(candidate_key)

            elif isinstance(node, ast.ClassDef):
                class_prefix = f"{prefix}.{node.name}" if prefix else node.name
                extract_from_scope(node.body, class_prefix, is_class=True)

    extract_from_scope(tree.body)

    # Post-process Queue C signals
    for cand in candidates:
        single_use_count = 0
        max_depth = 1 if cand.direct_private_helpers else 0

        candidate_key = (cand.symbol, cand.start_line)
        for helper_key in helper_keys_by_candidate.get(candidate_key, []):
            callers = helper_call_map.get(helper_key, set())
            if len(callers) == 1:
                single_use_count += 1

            helper_node = private_helper_defs.get(helper_key)
            if helper_node:
                helper_analyzer = _PythonFunctionASTAnalyzer(helper_node, source_lines)
                helper_analyzer.analyze()
                if helper_analyzer.called_private_helpers and max_depth < 2:
                    max_depth = 2

        cand.signals.single_use_private_helper_count = single_use_count
        cand.signals.private_call_depth = max_depth

    return candidates, True


def _extract_symbol_name(lang: str, text: str, context: str = "") -> str:
    """Extracts function/method symbol name from declaration text."""
    first_line = text.strip().splitlines()[0] if text.strip() else ""
    if lang == "swift":
        m = re.search(r"\bfunc\s+([A-Za-z0-9_]+)", text)
        return m.group(1) if m else "unknown"
    if lang in ("ts", "tsx", "js"):
        context_line = context.strip().splitlines()[0] if context.strip() else first_line
        m = re.search(r"\bfunction\s+([A-Za-z0-9_]+)", first_line)
        if m:
            return m.group(1)
        m = re.search(r"(?:const|let|var)\s+([A-Za-z0-9_]+)(?:\s*:[^=]+)?\s*=", context_line)
        if m:
            return m.group(1)
        m = re.search(
            r"(?:async\s+)?(?:static\s+|private\s+|public\s+|protected\s+)*([A-Za-z0-9_#]+)\s*\(",
            first_line,
        )
        if m and m.group(1) not in {"async", "function"}:
            return m.group(1)
        return "unknown"
    if lang == "go":
        m = re.search(r"func\s+(?:\([^\)]+\)\s+)?([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "rust":
        m = re.search(r"\bfn\s+([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "kotlin":
        m = re.search(r"\bfun\s+([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "java":
        m = re.search(
            r"(?:public|protected|private|static|final|\s)+[\w<>\[\],\s]+\s+([A-Za-z0-9_]+)\s*\(",
            first_line,
        )
        if m:
            return m.group(1)
        m = re.search(r"([A-Za-z0-9_]+)\s*\(", first_line)
        return m.group(1) if m else "unknown"
    return "unknown"


def _is_private_symbol(lang: str, name: str, text: str) -> bool:
    """Determines if a function/method is private."""
    if name.startswith("_") and not name.startswith("__"):
        return True
    if lang == "swift":
        return bool(
            re.search(
                r"\b(private|fileprivate)\s+(?:static\s+|final\s+|mutating\s+|nonisolated\s+)*func\b",
                text,
            )
        )
    if lang in ("ts", "tsx", "js"):
        return name.startswith("#") or bool(re.search(r"\bprivate\s+", text))
    if lang == "go":
        return bool(name and name[0].islower())
    if lang == "rust":
        return not bool(re.search(r"\bpub(?:\([^\)]+\))?\s+fn\b", text))
    if lang in ("kotlin", "java"):
        return bool(re.search(r"\bprivate\s+", text))
    return False


def _analyze_text_function(
    lang: str, name: str, text: str, start_line: int
) -> tuple[FunctionSignals, list[str]]:
    """Analyzes a non-Python function body text for signals."""
    sig = FunctionSignals()
    lines = _mask_source(text).splitlines()
    sig.logical_lines = sum(
        1 for line in lines if line.strip() and not line.strip().startswith("//")
    )

    # Queue A: Decisions & Nesting
    decisions = 0
    max_nesting = 0
    current_nesting = 0
    max_condition_operands = 1

    decision_pat = re.compile(
        r"\b(?:if|guard|for|while|catch|case|when|select|match)\b|&&|\|\||\?\?"
    )

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue

        open_b = stripped.count("{")
        close_b = stripped.count("}")
        current_nesting += open_b
        if current_nesting > max_nesting:
            max_nesting = current_nesting
        current_nesting -= close_b
        if current_nesting < 0:
            current_nesting = 0

        # Decisions
        hits = decision_pat.findall(stripped)
        decisions += len(hits)

        # Condition operands
        if any(w in stripped for w in ("if ", "guard ", "while ", "case ", "when ")):
            cond_count = len(re.findall(r"&&|\|\||and|or|\?\?", stripped)) + 1
            if cond_count > max_condition_operands:
                max_condition_operands = cond_count

    sig.decision_count = decisions
    sig.max_nesting = max(0, max_nesting - 1)  # offset outer function brace
    sig.condition_operand_max = max_condition_operands

    # Queue B: Mutations
    assignments: dict[str, list[int]] = defaultdict(list)
    assign_pat = re.compile(
        r"\b(?:var|let\s+mut|let)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(=|\+=|-=|\*=|/=|%=)"
    )
    reassign_pat = re.compile(
        r"\b([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)\s*(=|\+=|-=|\*=|/=|%=)(?!=)"
    )

    for idx, line in enumerate(lines, start=start_line):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue

        declared_on_line: set[str] = set()
        for m in assign_pat.finditer(stripped):
            var_name = m.group(1)
            assignments[var_name].append(idx)
            declared_on_line.add(var_name)

        for m in reassign_pat.finditer(stripped):
            var_name = m.group(1)
            if var_name not in declared_on_line and var_name not in (
                "if",
                "return",
                "let",
                "var",
                "const",
                "for",
                "while",
            ):
                assignments[var_name].append(idx)

    mutated_vars = {k: v for k, v in assignments.items() if len(v) >= 2}
    sig.mutable_local_count = len(mutated_vars)
    sig.distinct_mutated_fields = len(assignments)
    sig.mutation_sites = sum(len(v) - 1 for v in assignments.values() if len(v) >= 2)

    max_span = 0
    for assign_lines in assignments.values():
        if len(assign_lines) >= 2:
            span = max(assign_lines) - min(assign_lines)
            if span > max_span:
                max_span = span
    sig.mutation_span = max_span

    # Queue C: Calls
    call_pat = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")
    all_calls: set[str] = set()
    for line in lines:
        for m in call_pat.finditer(line):
            fn = m.group(1)
            if fn not in (
                "if",
                "for",
                "while",
                "switch",
                "catch",
                "guard",
                "when",
                "select",
                "match",
                name,
            ):
                all_calls.add(fn)

    sig.direct_call_fanout = len(all_calls)
    return sig, sorted(all_calls)


def _ast_grep_matches(
    ast_grep_bin: str, path: Path, lang: str, selector: str
) -> tuple[list[dict], bool]:
    cmd = [
        ast_grep_bin,
        "run",
        "--lang",
        lang,
        "--kind",
        selector,
        "--json=compact",
        str(path),
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except (subprocess.TimeoutExpired, OSError):
        return [], False
    if proc.returncode != 0:
        return [], False
    if not proc.stdout.strip():
        return [], True
    try:
        matches = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return [], False
    return (matches, True) if isinstance(matches, list) else ([], False)


def _match_offsets(match: dict) -> tuple[int, int]:
    offsets = match.get("range", {}).get("byteOffset", {})
    return int(offsets.get("start", 0)), int(offsets.get("end", 0))


def _match_lines(match: dict) -> tuple[int, int]:
    match_range = match.get("range", {})
    start = int(match_range.get("start", {}).get("line", 0)) + 1
    end = int(match_range.get("end", {}).get("line", 0)) + 1
    return start, end


def _swift_type_name(text: str) -> str:
    match = re.search(r"\b(?:class|struct|actor|enum|extension)\s+([A-Za-z_][A-Za-z0-9_]*)", text)
    return match.group(1) if match else ""


def _smallest_container(start: int, end: int, ranges: list[tuple[int, int, str]]) -> str:
    containers = [item for item in ranges if item[0] <= start and end <= item[1]]
    return min(containers, key=lambda item: item[1] - item[0])[2] if containers else ""


def _swift_node_category(text: str) -> str:
    stripped = _mask_source(text).lstrip()
    header = stripped.split("{", 1)[0]
    if re.search(r"\b(?:class|struct|actor|enum|extension)\s+[A-Za-z_]", header):
        return "type"
    if re.match(r"(?:if|guard|for|while|catch|case|default)\b", stripped):
        return "decision"
    if stripped.startswith("switch "):
        return "nesting"
    if "&&" in stripped or "||" in stripped:
        return "logic"
    if re.match(r"(?:var|let)\s+[A-Za-z_]", stripped) or re.search(
        r"(?:\+=|-=|\*=|/=|%=|(?<![=!<>])=(?!=))", stripped
    ):
        return "mutation"
    return "call"


def _swift_assignment_name(text: str) -> str:
    declaration = re.search(r"\b(?:var|let)\s+([A-Za-z_][A-Za-z0-9_]*)", text)
    if declaration:
        return declaration.group(1)
    assignment = re.match(
        r"\s*([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)\s*"
        r"(?:\+=|-=|\*=|/=|%=|=)",
        text,
    )
    return assignment.group(1) if assignment else ""


def _call_name(text: str) -> str:
    prefix = text.split("(", 1)[0]
    identifiers = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", prefix)
    return identifiers[-1] if identifiers else ""


def _analyze_swift_function(
    function_match: dict,
    node_matches: list[dict],
    function_ranges: list[tuple[int, int, str]],
) -> tuple[FunctionSignals, list[str]]:
    function_start, function_end = _match_offsets(function_match)
    function_id = f"{function_start}:{function_end}"
    owned_nodes: list[tuple[dict, int, int, str]] = []
    for node in node_matches:
        node_start, node_end = _match_offsets(node)
        if _smallest_container(node_start, node_end, function_ranges) != function_id:
            continue
        category = _swift_node_category(str(node.get("text", "")))
        if category != "type":
            owned_nodes.append((node, node_start, node_end, category))

    signals = FunctionSignals()
    masked_lines = _mask_source(str(function_match.get("text", ""))).splitlines()
    signals.logical_lines = sum(1 for line in masked_lines if line.strip())

    decisions = [node for node in owned_nodes if node[3] == "decision"]
    logic = [node for node in owned_nodes if node[3] == "logic"]
    nesting = [node for node in owned_nodes if node[3] in {"decision", "nesting"}]
    signals.decision_count = len(decisions) + len(logic)
    signals.max_nesting = max(
        (
            1
            + sum(
                1
                for other in nesting
                if other is not node and other[1] <= node[1] and node[2] <= other[2]
            )
            for node in decisions
        ),
        default=0,
    )
    signals.condition_operand_max = max(
        (
            1
            + sum(
                1 for logic_node in logic if node[1] <= logic_node[1] and logic_node[2] <= node[2]
            )
            for node in decisions
        ),
        default=0,
    )

    assignments: dict[str, list[int]] = defaultdict(list)
    for node, _, _, category in owned_nodes:
        if category != "mutation":
            continue
        name = _swift_assignment_name(str(node.get("text", "")))
        if name:
            assignments[name].append(_match_lines(node)[0])
    mutated = {name: lines for name, lines in assignments.items() if len(lines) >= 2}
    signals.mutable_local_count = len(mutated)
    signals.distinct_mutated_fields = len(assignments)
    signals.mutation_sites = sum(len(lines) - 1 for lines in mutated.values())
    signals.mutation_span = max((max(lines) - min(lines) for lines in mutated.values()), default=0)

    calls = {
        name
        for node, _, _, category in owned_nodes
        if category == "call"
        if (name := _call_name(str(node.get("text", ""))))
    }
    signals.direct_call_fanout = len(calls)
    return signals, sorted(calls)


def _wire_private_helpers(records: list[_ScannedFunction]) -> None:
    private_defs: dict[tuple[str, str], list[_ScannedFunction]] = defaultdict(list)
    for record in records:
        if record.is_private:
            private_defs[(record.owner, record.name)].append(record)

    resolved_calls: dict[int, list[tuple[str, str]]] = {}
    callers: dict[tuple[str, str], set[tuple[str, int, int]]] = defaultdict(set)
    for record in records:
        keys = [
            (record.owner, call)
            for call in record.direct_calls
            if len(private_defs.get((record.owner, call), [])) == 1
        ]
        resolved_calls[id(record)] = keys
        identity = (
            record.candidate.path,
            record.candidate.start_line,
            record.candidate.end_line,
        )
        for key in keys:
            callers[key].add(identity)

    for record in records:
        keys = resolved_calls[id(record)]
        record.candidate.direct_private_helpers = sorted({name for _, name in keys})
        record.candidate.signals.private_helper_fanout = len(
            record.candidate.direct_private_helpers
        )
        record.candidate.signals.single_use_private_helper_count = sum(
            1 for key in keys if len(callers[key]) == 1
        )
        record.candidate.signals.private_call_depth = 1 if keys else 0
        for key in keys:
            helper = private_defs[key][0]
            if resolved_calls.get(id(helper)):
                record.candidate.signals.private_call_depth = 2
                break


def scan_non_python_file(
    path: Path, lang: str, repo_root: Path
) -> tuple[list[CandidateSymbol], bool]:
    """Scans a non-Python file using ast-grep for candidate symbols."""
    ast_grep_bin = shutil.which("ast-grep") or shutil.which("sg")
    if not ast_grep_bin:
        return [], False

    declarations: list[dict] = []
    complete = True
    for kind in AST_GREP_KINDS.get(lang, ["function_declaration"]):
        matches, ok = _ast_grep_matches(ast_grep_bin, path, lang, kind)
        declarations.extend(matches)
        complete = complete and ok

    swift_nodes: list[dict] = []
    type_ranges: list[tuple[int, int, str]] = []
    if lang == "swift":
        swift_nodes, ok = _ast_grep_matches(ast_grep_bin, path, lang, _SWIFT_NODE_SELECTOR)
        complete = complete and ok
        for node in swift_nodes:
            owner = _swift_type_name(str(node.get("text", "")))
            if owner and _swift_node_category(str(node.get("text", ""))) == "type":
                start, end = _match_offsets(node)
                type_ranges.append((start, end, owner))

    function_ranges = [
        (*_match_offsets(match), f"{_match_offsets(match)[0]}:{_match_offsets(match)[1]}")
        for match in declarations
    ]
    rel_path = str(path.relative_to(repo_root))
    records: list[_ScannedFunction] = []
    for match in declarations:
        text = str(match.get("text", ""))
        context = str(match.get("lines", ""))
        name = _extract_symbol_name(lang, text, context)
        if name == "unknown" or len(text.strip()) < 10:
            continue
        start_line, end_line = _match_lines(match)
        start_offset, end_offset = _match_offsets(match)
        owner = (
            _smallest_container(start_offset, end_offset, type_ranges) if lang == "swift" else ""
        )
        symbol = f"{owner}.{name}" if owner else name
        if lang == "swift":
            signals, direct_calls = _analyze_swift_function(match, swift_nodes, function_ranges)
        else:
            signals, direct_calls = _analyze_text_function(lang, name, text, start_line)
        candidate = CandidateSymbol(
            path=rel_path,
            symbol=symbol,
            start_line=start_line,
            end_line=end_line,
            signals=signals,
        )
        records.append(
            _ScannedFunction(
                candidate=candidate,
                owner=owner,
                name=name,
                direct_calls=direct_calls,
                is_private=_is_private_symbol(lang, name, text),
            )
        )

    _wire_private_helpers(records)
    return [record.candidate for record in records], complete


def rank_and_select(
    candidates: list[CandidateSymbol], top_k_per_queue: int = 2
) -> tuple[list[CandidateSymbol], dict[str, list[CandidateSymbol]]]:
    """Ranks candidates across the 3 queues and selects top candidates."""
    q_control = [
        c for c in candidates if c.signals.decision_count >= 3 or c.signals.max_nesting >= 2
    ]
    q_mutation = [
        c for c in candidates if c.signals.mutation_sites >= 2 and c.signals.mutation_span >= 5
    ]
    q_navigation = [
        c
        for c in candidates
        if c.signals.single_use_private_helper_count >= 1 or c.signals.private_helper_fanout >= 2
    ]

    q_control.sort(key=lambda c: c.control_score, reverse=True)
    q_mutation.sort(key=lambda c: c.mutation_score, reverse=True)
    q_navigation.sort(key=lambda c: c.navigation_score, reverse=True)

    top_control = q_control[:top_k_per_queue]
    top_mutation = q_mutation[:top_k_per_queue]
    top_navigation = q_navigation[:top_k_per_queue]

    eligibility: dict[tuple[str, int, int], list[str]] = defaultdict(list)
    for queue, queue_candidates in (
        ("control", q_control),
        ("mutation", q_mutation),
        ("navigation", q_navigation),
    ):
        for candidate in queue_candidates:
            eligibility[(candidate.path, candidate.start_line, candidate.end_line)].append(queue)

    selected_dict: dict[tuple[str, int, int], CandidateSymbol] = {}

    for candidate in top_control + top_mutation + top_navigation:
        key = (candidate.path, candidate.start_line, candidate.end_line)
        selected_dict.setdefault(key, candidate)

    for key, candidate in selected_dict.items():
        candidate.candidate_queues = eligibility[key]

    for cand in selected_dict.values():
        scores = {
            "control": cand.control_score,
            "mutation": cand.mutation_score,
            "navigation": cand.navigation_score,
        }
        cand.primary_queue = max(cand.candidate_queues, key=lambda q: scores.get(q, 0))

    final_roster = list(selected_dict.values())
    queue_rosters = {
        "control": top_control,
        "mutation": top_mutation,
        "navigation": top_navigation,
    }
    return final_roster, queue_rosters


def _json_document(
    status: str,
    coverage: dict[str, dict[str, int | str]],
    roster: list[CandidateSymbol],
    queue_rosters: dict[str, list[CandidateSymbol]],
) -> dict:
    return {
        "schema_version": 2,
        "status": status,
        "coverage": coverage,
        "doctrine": (
            "Candidate evidence for Critic Method Step 6 (promotion_allowed: false). "
            "Metrics support judgment; they never decide it. The Critic independently "
            "validates candidate symbols against source."
        ),
        "promotion_allowed": False,
        "candidates": [
            {
                "path": candidate.path,
                "symbol": candidate.symbol,
                "line_range": {"start": candidate.start_line, "end": candidate.end_line},
                "candidate_queues": candidate.candidate_queues,
                "primary_queue": candidate.primary_queue,
                "signals": asdict(candidate.signals),
                "neighborhood": {"direct_private_helpers": candidate.direct_private_helpers},
            }
            for candidate in roster
        ],
        "queue_counts": {
            queue: len(queue_rosters.get(queue, []))
            for queue in ("control", "mutation", "navigation")
        },
    }


def main() -> int:
    _force_utf8_stdout()
    parser = argparse.ArgumentParser(
        description="audit_hotspots.py — implementation-hotspot candidate scanner."
    )
    parser.add_argument(
        "repo_root",
        nargs="?",
        default=".",
        help="Target repository root directory (default: current directory)",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=2,
        help="Top candidates per queue to select (default: 2, max deduplicated: 6)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit structured JSON with promotion_allowed: false",
    )
    args = parser.parse_args()

    if args.top_k < 1:
        parser.error("--top-k must be at least 1")

    repo_dir = Path(args.repo_root).resolve()
    if not repo_dir.is_dir():
        sys.stderr.write(f"error: '{repo_dir}' is not a directory\n")
        return 2

    # Discover source files
    py_files: list[Path] = []
    non_py_files: list[tuple[Path, str]] = []

    for p in sorted(repo_dir.rglob("*")):
        if not p.is_file():
            continue
        if any(part in IGNORE_DIRS for part in p.parts):
            continue
        if _is_test_file(p.name) or _is_generated_file(p):
            continue

        ext = p.suffix.lower()
        if ext == ".py":
            py_files.append(p)
        elif ext in _LANG_BY_EXT:
            non_py_files.append((p, _LANG_BY_EXT[ext]))

    ast_grep_bin = shutil.which("ast-grep") or shutil.which("sg")
    ast_grep_missing = non_py_files and not ast_grep_bin

    coverage: dict[str, dict[str, int | str]] = {
        "python": {"discovered": len(py_files), "scanned": 0, "failed": 0},
        "ast_grep": {
            "discovered": len(non_py_files),
            "scanned": 0,
            "failed": 0,
            "outcome": "not_applicable" if not non_py_files else "ok",
        },
    }

    if not py_files and not non_py_files:
        if args.json:
            doc = _json_document(
                "not_applicable",
                coverage,
                [],
                {"control": [], "mutation": [], "navigation": []},
            )
            sys.stdout.write(json.dumps(doc, indent=2) + "\n")
        else:
            sys.stderr.write("audit_hotspots: no supported source files identified.\n")
        return 0

    if not py_files and ast_grep_missing:
        # Only non-Python files exist, and ast-grep is absent: skip gracefully with install guidance
        coverage["ast_grep"].update({"failed": len(non_py_files), "outcome": "absent"})
        if args.json:
            doc = _json_document(
                "absent",
                coverage,
                [],
                {"control": [], "mutation": [], "navigation": []},
            )
            doc.update(
                {
                    "tool": "ast-grep",
                    "install_instructions": INSTALL_INSTRUCTIONS,
                }
            )
            sys.stdout.write(json.dumps(doc, indent=2) + "\n")
        else:
            sys.stderr.write(
                f"audit_hotspots: 'ast-grep' not found on PATH. Multi-language scanning skipped for "
                f"{len(non_py_files)} file(s).\n"
                f"To install ast-grep: {INSTALL_INSTRUCTIONS}\n"
            )
        return 0

    # Collect candidates
    candidates: list[CandidateSymbol] = []
    for p in py_files:
        file_candidates, complete = scan_python_file(p, repo_dir)
        candidates.extend(file_candidates)
        coverage["python"]["scanned" if complete else "failed"] += 1

    if not ast_grep_missing:
        for p, lang in non_py_files:
            file_candidates, complete = scan_non_python_file(p, lang, repo_dir)
            candidates.extend(file_candidates)
            coverage["ast_grep"]["scanned" if complete else "failed"] += 1
        if coverage["ast_grep"]["failed"]:
            coverage["ast_grep"]["outcome"] = "partial"
    elif non_py_files:
        coverage["ast_grep"].update({"failed": len(non_py_files), "outcome": "absent"})
        sys.stderr.write(
            f"audit_hotspots: 'ast-grep' not found on PATH. Skipped {len(non_py_files)} non-Python file(s). "
            f"To install: {INSTALL_INSTRUCTIONS}\n"
        )

    roster, queue_rosters = rank_and_select(candidates, top_k_per_queue=args.top_k)
    incomplete = bool(coverage["python"]["failed"] or coverage["ast_grep"]["failed"])
    status = "partial" if incomplete else "ok"

    if args.json:
        doc = _json_document(status, coverage, roster, queue_rosters)
        if ast_grep_missing:
            doc["tool_notice"] = {
                "tool": "ast-grep",
                "status": "absent",
                "install_instructions": INSTALL_INSTRUCTIONS,
            }
        sys.stdout.write(json.dumps(doc, indent=2) + "\n")
        return 0

    if not roster:
        sys.stderr.write("audit_hotspots: no implementation hotspots identified.\n")
        return 0

    print("### Implementation Hotspot Candidates (`promotion_allowed: false`)")
    print(
        "*Advisory candidate evidence for Critic Method Step 6.* "
        "*Run 3-way triage (confirm | contextualize | dismiss) against source semantics before forming findings.*\n"
    )
    print("| Symbol | File:Lines | Queues | Key Signals | Direct Helpers |")
    print("|---|---|---|---|---|")
    for c in roster:
        queues_str = ", ".join(c.candidate_queues)
        sig = c.signals
        key_sigs = (
            f"decisions={sig.decision_count}, nesting={sig.max_nesting}, "
            f"mut_span={sig.mutation_span}, single_helpers={sig.single_use_private_helper_count}"
        )
        helpers_str = ", ".join(c.direct_private_helpers) if c.direct_private_helpers else "none"
        print(
            f"| `{c.symbol}` | `{c.path}:{c.start_line}-{c.end_line}` | {queues_str} | {key_sigs} | {helpers_str} |"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
