#!/usr/bin/env python3
# WAIVER: module-size — standalone multi-language hotspot candidate scanner
#   (Python stdlib AST + ast-grep multi-language engine + Queue A/B/C cognitive
#   reasoning signal extractors + JSON epistemic reporter). Self-contained single-file
#   CLI helper for Step 6 candidate evidence.
"""audit_hotspots.py — candidate-evidence detector for implementation hotspots.

Mechanical helper for Method Step 6 (Review simplification & clarity).
Identifies functions and methods exhibiting high cognitive reasoning burden across
three independent candidate queues:
  - Queue A: Control Reasoning Density (decisions, nesting, complex condition operands)
  - Queue B: Temporal Mutation & State Reasoning (mutation span, reassignments across branches)
  - Queue C: Private Navigation Fragmentation (single-use private helpers, helper call depth)

EPISTEMIC CONTRACT (Meta-Rule 1):
  Output is CANDIDATE EVIDENCE for the Critic (promotion_allowed: false).
  Metrics support judgment; they never decide it.
  The Critic independently inspects the symbol and its immediate private neighborhood,
  deriving any findings strictly from source semantics (Claim → Source → Consequence → Remedy).
  No metric score or threshold may appear in findings, severity ratings, or scorecards.

Supported stacks:
  - Python (via stdlib ast)
  - Swift, TypeScript, JavaScript, Go, Rust, Kotlin, Java (via open-source ast-grep)
  If ast-grep is not installed on non-Python repositories, multi-language scanning
  is skipped gracefully with installation instructions.

Usage:
  scripts/audit_hotspots.py [<repo-root>] [--top-k N] [--json]

Exit codes:
  0 = ran (with or without candidates, or skipped-absent/clean)
  2 = usage error (bad path or arguments)
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path

# Directory names never scanned: VCS/build/cache/vendor + test + generated trees.
IGNORE_DIRS = frozenset(
    {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        ".env",
        "build",
        "dist",
        ".tox",
        ".mypy_cache",
        ".pytest_cache",
        "site-packages",
        "migrations",
        "tests",
        "test",
        ".eggs",
        ".build",
        "DerivedData",
        "target",
        ".gradle",
        "bin",
        "obj",
        "vendor",
    }
)

_GENERATED_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "Generated by",
    "AUTOGENERATED",
    "code generated by",
)

_LANG_BY_EXT: dict[str, str] = {
    ".py": "python",
    ".swift": "swift",
    ".ts": "ts",
    ".tsx": "tsx",
    ".js": "js",
    ".jsx": "js",
    ".mjs": "js",
    ".cjs": "js",
    ".go": "go",
    ".rs": "rust",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".java": "java",
}

AST_GREP_KINDS: dict[str, list[str]] = {
    "swift": ["function_declaration"],
    "ts": ["function_declaration", "method_definition", "arrow_function"],
    "tsx": ["function_declaration", "method_definition", "arrow_function"],
    "js": ["function_declaration", "method_definition", "arrow_function"],
    "go": ["function_declaration", "method_declaration"],
    "rust": ["function_item"],
    "kotlin": ["function_declaration"],
    "java": ["method_declaration", "constructor_declaration"],
}

INSTALL_INSTRUCTIONS = (
    "brew install ast-grep (macOS/Homebrew) | "
    "cargo install ast-grep-cli (Rust/Cargo) | "
    "npm install -g @ast-grep/cli (Node/NPM)"
)


def _force_utf8_stdout() -> None:
    """Emit UTF-8 regardless of console code page."""
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")


def _is_test_file(name: str) -> bool:
    lower = name.lower()
    return lower.startswith("test_") or lower.endswith(
        (
            "_test.py",
            "_test.go",
            "_test.rs",
            "tests.swift",
            "test.swift",
            "spec.swift",
            ".test.ts",
            ".spec.ts",
            ".test.tsx",
            ".spec.tsx",
            ".test.js",
            ".spec.js",
            "test.kt",
            "tests.kt",
            "test.java",
            "tests.java",
        )
    )


def _is_generated_file(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:1024]
        return any(marker.lower() in head.lower() for marker in _GENERATED_MARKERS)
    except OSError:
        return False


@dataclass
class FunctionSignals:
    decision_count: int = 0
    max_nesting: int = 0
    condition_operand_max: int = 0
    logical_lines: int = 0

    mutation_sites: int = 0
    mutation_span: int = 0
    distinct_mutated_fields: int = 0
    mutable_local_count: int = 0

    private_helper_fanout: int = 0
    single_use_private_helper_count: int = 0
    private_call_depth: int = 0
    direct_call_fanout: int = 0


@dataclass
class CandidateSymbol:
    path: str
    symbol: str
    start_line: int
    end_line: int
    signals: FunctionSignals
    candidate_queues: list[str] = field(default_factory=list)
    primary_queue: str = ""
    direct_private_helpers: list[str] = field(default_factory=list)

    @property
    def control_score(self) -> int:
        return (
            self.signals.decision_count * 3
            + self.signals.max_nesting * 4
            + self.signals.condition_operand_max * 2
            + (self.signals.logical_lines // 10)
        )

    @property
    def mutation_score(self) -> int:
        return (
            self.signals.mutation_span * 2
            + self.signals.mutation_sites * 3
            + self.signals.distinct_mutated_fields * 2
            + self.signals.mutable_local_count * 4
        )

    @property
    def navigation_score(self) -> int:
        return (
            self.signals.single_use_private_helper_count * 20
            + self.signals.private_helper_fanout * 5
            + self.signals.private_call_depth * 8
            + self.signals.direct_call_fanout
        )


class _PythonFunctionASTAnalyzer(ast.NodeVisitor):
    """Analyzes a single Python FunctionDef / AsyncFunctionDef AST node."""

    def __init__(
        self, fn_node: ast.FunctionDef | ast.AsyncFunctionDef, source_lines: list[str]
    ) -> None:
        self.fn_node = fn_node
        self.source_lines = source_lines
        self.signals = FunctionSignals()
        self.called_functions: set[str] = set()
        self.called_private_helpers: set[str] = set()

        self.var_assignments: dict[str, list[int]] = defaultdict(list)
        self.var_reads: dict[str, list[int]] = defaultdict(list)

    def analyze(self) -> FunctionSignals:
        start = self.fn_node.lineno - 1
        end = getattr(self.fn_node, "end_lineno", self.fn_node.lineno)
        body_lines = self.source_lines[start:end]
        self.signals.logical_lines = sum(
            1 for line in body_lines if line.strip() and not line.strip().startswith("#")
        )

        self._walk_body(self.fn_node.body, depth=0)
        self._compute_mutation_signals()

        self.signals.direct_call_fanout = len(self.called_functions)
        self.signals.private_helper_fanout = len(self.called_private_helpers)
        return self.signals

    def _walk_body(self, nodes: list[ast.stmt], depth: int) -> None:
        for node in nodes:
            self._process_stmt(node, depth)

    def _process_stmt(self, node: ast.AST, depth: int) -> None:
        if depth > self.signals.max_nesting:
            self.signals.max_nesting = depth

        if isinstance(node, ast.If):
            self.signals.decision_count += 1
            self._analyze_condition(node.test)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                    self._process_stmt(node.orelse[0], depth)
                else:
                    self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, (ast.For, ast.AsyncFor)):
            self.signals.decision_count += 1
            self._extract_assign_targets(node.target, node.lineno)
            self.visit(node.iter)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, ast.While):
            self.signals.decision_count += 1
            self._analyze_condition(node.test)
            self._walk_body(node.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)

        elif isinstance(node, ast.Try):
            self._walk_body(node.body, depth + 1)
            for handler in node.handlers:
                self.signals.decision_count += 1
                if handler.name:
                    self.var_assignments[handler.name].append(handler.lineno)
                self._walk_body(handler.body, depth + 1)
            if node.orelse:
                self._walk_body(node.orelse, depth + 1)
            if node.finalbody:
                self._walk_body(node.finalbody, depth + 1)

        elif isinstance(node, (ast.With, ast.AsyncWith)):
            for item in node.items:
                if item.optional_vars:
                    self._extract_assign_targets(item.optional_vars, node.lineno)
                self.visit(item.context_expr)
            self._walk_body(node.body, depth + 1)

        elif isinstance(node, getattr(ast, "Match", ())):  # Python 3.10+
            self.visit(node.subject)
            for case in node.cases:
                self.signals.decision_count += 1
                if case.guard:
                    self._analyze_condition(case.guard)
                self._walk_body(case.body, depth + 1)

        elif isinstance(node, ast.Assign):
            for target in node.targets:
                self._extract_assign_targets(target, node.lineno)
            self.visit(node.value)

        elif isinstance(node, ast.AugAssign):
            self._extract_assign_targets(node.target, node.lineno)
            self.visit(node.value)

        elif isinstance(node, ast.AnnAssign):
            self._extract_assign_targets(node.target, node.lineno)
            if node.value:
                self.visit(node.value)

        else:
            self.visit(node)

    def _analyze_condition(self, expr: ast.AST) -> None:
        count = 1
        for sub in ast.walk(expr):
            if isinstance(sub, ast.BoolOp):
                count += len(sub.values) - 1
                self.signals.decision_count += len(sub.values) - 1
            elif isinstance(sub, ast.Compare):
                count += len(sub.ops) - 1
            elif isinstance(sub, ast.IfExp):
                self.signals.decision_count += 1
        if count > self.signals.condition_operand_max:
            self.signals.condition_operand_max = count

    def _extract_assign_targets(self, target: ast.AST, lineno: int) -> None:
        if isinstance(target, ast.Name):
            self.var_assignments[target.id].append(lineno)
        elif isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name):
            if target.value.id == "self":
                self.var_assignments[f"self.{target.attr}"].append(lineno)
        elif isinstance(target, (ast.Tuple, ast.List)):
            for elt in target.elts:
                self._extract_assign_targets(elt, lineno)

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load):
            self.var_reads[node.id].append(node.lineno)
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if (
            isinstance(node.ctx, ast.Load)
            and isinstance(node.value, ast.Name)
            and node.value.id == "self"
        ):
            self.var_reads[f"self.{node.attr}"].append(node.lineno)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        fn_name = ""
        is_private = False
        if isinstance(node.func, ast.Name):
            fn_name = node.func.id
            if fn_name.startswith("_") and not fn_name.startswith("__"):
                is_private = True
        elif isinstance(node.func, ast.Attribute):
            fn_name = node.func.attr
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id == "self"
                and fn_name.startswith("_")
                and not fn_name.startswith("__")
            ):
                is_private = True

        if fn_name:
            self.called_functions.add(fn_name)
            if is_private:
                self.called_private_helpers.add(fn_name)

        self.generic_visit(node)

    def _compute_mutation_signals(self) -> None:
        mutated_vars = {k: v for k, v in self.var_assignments.items() if len(v) >= 2}
        self.signals.mutable_local_count = len(mutated_vars)
        self.signals.distinct_mutated_fields = len(
            [k for k, v in self.var_assignments.items() if len(v) >= 2 or k.startswith("self.")]
        )
        self.signals.mutation_sites = sum(
            len(v) - 1 for v in self.var_assignments.values() if len(v) >= 2
        )

        max_span = 0
        for var_name, assign_lines in self.var_assignments.items():
            if len(assign_lines) >= 2 or (var_name.startswith("self.") and assign_lines):
                first_assign = assign_lines[0]
                reads = self.var_reads.get(var_name, [])
                all_accesses = assign_lines + reads
                last_access = max(all_accesses) if all_accesses else first_assign
                span = last_access - first_assign
                if span > max_span:
                    max_span = span

        self.signals.mutation_span = max_span


def scan_python_file(path: Path, repo_root: Path) -> list[CandidateSymbol]:
    """Scans a single Python file for function & method candidate symbols."""
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, OSError, UnicodeDecodeError):
        return []

    source_lines = source.splitlines()
    rel_path = str(path.relative_to(repo_root))

    candidates: list[CandidateSymbol] = []
    helper_call_map: dict[str, set[str]] = defaultdict(set)
    private_helper_defs: dict[str, ast.FunctionDef | ast.AsyncFunctionDef] = {}

    def extract_from_scope(nodes: list[ast.stmt], prefix: str = "", is_class: bool = False) -> None:
        for node in nodes:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                symbol_name = f"{prefix}.{node.name}" if prefix else node.name
                analyzer = _PythonFunctionASTAnalyzer(node, source_lines)
                signals = analyzer.analyze()

                candidate = CandidateSymbol(
                    path=rel_path,
                    symbol=symbol_name,
                    start_line=node.lineno,
                    end_line=getattr(node, "end_lineno", node.lineno),
                    signals=signals,
                    direct_private_helpers=sorted(analyzer.called_private_helpers),
                )
                candidates.append(candidate)

                if node.name.startswith("_") and not node.name.startswith("__"):
                    private_helper_defs[node.name] = node

                for helper in analyzer.called_private_helpers:
                    helper_call_map[helper].add(symbol_name)

            elif isinstance(node, ast.ClassDef):
                class_prefix = f"{prefix}.{node.name}" if prefix else node.name
                extract_from_scope(node.body, class_prefix, is_class=True)

    extract_from_scope(tree.body)

    # Post-process Queue C signals
    for cand in candidates:
        single_use_count = 0
        max_depth = 1 if cand.direct_private_helpers else 0

        for helper in cand.direct_private_helpers:
            callers = helper_call_map.get(helper, set())
            if len(callers) == 1:
                single_use_count += 1

            helper_node = private_helper_defs.get(helper)
            if helper_node:
                helper_analyzer = _PythonFunctionASTAnalyzer(helper_node, source_lines)
                helper_analyzer.analyze()
                if helper_analyzer.called_private_helpers and max_depth < 2:
                    max_depth = 2

        cand.signals.single_use_private_helper_count = single_use_count
        cand.signals.private_call_depth = max_depth

    return candidates


def _extract_symbol_name(lang: str, text: str) -> str:
    """Extracts function/method symbol name from declaration text."""
    first_line = text.strip().splitlines()[0] if text.strip() else ""
    if lang == "swift":
        m = re.search(r"\bfunc\s+([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang in ("ts", "tsx", "js"):
        m = re.search(r"\bfunction\s+([A-Za-z0-9_]+)", first_line)
        if m:
            return m.group(1)
        m = re.search(r"(?:const|let|var)\s+([A-Za-z0-9_]+)\s*=", first_line)
        if m:
            return m.group(1)
        m = re.search(
            r"(?:async\s+)?(?:static\s+|private\s+|public\s+|protected\s+)*([A-Za-z0-9_#]+)\s*\(",
            first_line,
        )
        if m:
            return m.group(1)
        return "unknown"
    if lang == "go":
        m = re.search(r"func\s+(?:\([^\)]+\)\s+)?([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "rust":
        m = re.search(r"\bfn\s+([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "kotlin":
        m = re.search(r"\bfun\s+([A-Za-z0-9_]+)", first_line)
        return m.group(1) if m else "unknown"
    if lang == "java":
        m = re.search(
            r"(?:public|protected|private|static|final|\s)+[\w<>\[\],\s]+\s+([A-Za-z0-9_]+)\s*\(",
            first_line,
        )
        if m:
            return m.group(1)
        m = re.search(r"([A-Za-z0-9_]+)\s*\(", first_line)
        return m.group(1) if m else "unknown"
    return "unknown"


def _is_private_symbol(lang: str, name: str, text: str) -> bool:
    """Determines if a function/method is private."""
    if name.startswith("_") and not name.startswith("__"):
        return True
    if lang == "swift":
        return bool(
            re.search(
                r"\b(private|fileprivate)\s+(?:static\s+|final\s+|mutating\s+|nonisolated\s+)*func\b",
                text,
            )
        )
    if lang in ("ts", "tsx", "js"):
        return name.startswith("#") or bool(re.search(r"\bprivate\s+", text))
    if lang == "go":
        return bool(name and name[0].islower())
    if lang == "rust":
        return not bool(re.search(r"\bpub(?:\([^\)]+\))?\s+fn\b", text))
    if lang in ("kotlin", "java"):
        return bool(re.search(r"\bprivate\s+", text))
    return False


def _analyze_text_function(
    lang: str, name: str, text: str, start_line: int
) -> tuple[FunctionSignals, list[str]]:
    """Analyzes a non-Python function body text for signals."""
    sig = FunctionSignals()
    lines = text.splitlines()
    sig.logical_lines = sum(
        1 for line in lines if line.strip() and not line.strip().startswith("//")
    )

    # Queue A: Decisions & Nesting
    decisions = 0
    max_nesting = 0
    current_nesting = 0
    max_condition_operands = 1

    decision_pat = re.compile(
        r"\b(?:if|guard|for|while|catch|case|when|select|match)\b|&&|\|\||\?\?"
    )

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue

        # Strip string literals before counting braces to avoid template string / placeholder spikes
        clean_line = re.sub(
            r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`', '""', stripped
        )
        open_b = clean_line.count("{")
        close_b = clean_line.count("}")
        current_nesting += open_b
        if current_nesting > max_nesting:
            max_nesting = current_nesting
        current_nesting -= close_b
        if current_nesting < 0:
            current_nesting = 0

        # Decisions
        hits = decision_pat.findall(stripped)
        decisions += len(hits)

        # Condition operands
        if any(w in stripped for w in ("if ", "guard ", "while ", "case ", "when ")):
            cond_count = len(re.findall(r"&&|\|\||and|or|\?\?", stripped)) + 1
            if cond_count > max_condition_operands:
                max_condition_operands = cond_count

    sig.decision_count = decisions
    sig.max_nesting = max(0, max_nesting - 1)  # offset outer function brace
    sig.condition_operand_max = max_condition_operands

    # Queue B: Mutations
    assignments: dict[str, list[int]] = defaultdict(list)
    assign_pat = re.compile(
        r"\b(?:var|let\s+mut|let)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(=|\+=|-=|\*=|/=|%=)"
    )
    reassign_pat = re.compile(
        r"\b([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)\s*(=|\+=|-=|\*=|/=|%=)(?!=)"
    )

    for idx, line in enumerate(lines, start=start_line):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue

        declared_on_line: set[str] = set()
        for m in assign_pat.finditer(stripped):
            var_name = m.group(1)
            assignments[var_name].append(idx)
            declared_on_line.add(var_name)

        for m in reassign_pat.finditer(stripped):
            var_name = m.group(1)
            if var_name not in declared_on_line and var_name not in (
                "if",
                "return",
                "let",
                "var",
                "const",
                "for",
                "while",
            ):
                assignments[var_name].append(idx)

    mutated_vars = {k: v for k, v in assignments.items() if len(v) >= 2}
    sig.mutable_local_count = len(mutated_vars)
    sig.distinct_mutated_fields = len(assignments)
    sig.mutation_sites = sum(len(v) - 1 for v in assignments.values() if len(v) >= 2)

    max_span = 0
    for assign_lines in assignments.values():
        if len(assign_lines) >= 2:
            span = max(assign_lines) - min(assign_lines)
            if span > max_span:
                max_span = span
    sig.mutation_span = max_span

    # Queue C: Calls
    call_pat = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")
    all_calls: set[str] = set()
    for line in lines:
        for m in call_pat.finditer(line):
            fn = m.group(1)
            if fn not in (
                "if",
                "for",
                "while",
                "switch",
                "catch",
                "guard",
                "when",
                "select",
                "match",
                name,
            ):
                all_calls.add(fn)

    sig.direct_call_fanout = len(all_calls)
    return sig, sorted(all_calls)


def scan_non_python_file(path: Path, lang: str, repo_root: Path) -> list[CandidateSymbol]:
    """Scans a non-Python file using ast-grep for candidate symbols."""
    ast_grep_bin = shutil.which("ast-grep") or shutil.which("sg")
    if not ast_grep_bin:
        return []

    kinds = AST_GREP_KINDS.get(lang, ["function_declaration"])
    rel_path = str(path.relative_to(repo_root))
    candidates: list[CandidateSymbol] = []
    helper_call_map: dict[str, set[str]] = defaultdict(set)
    private_defs: dict[str, tuple[FunctionSignals, list[str]]] = {}

    for kind in kinds:
        cmd = [ast_grep_bin, "run", "--lang", lang, "--kind", kind, "--json=compact", str(path)]
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        except (subprocess.TimeoutExpired, OSError):
            continue

        if proc.returncode != 0 or not proc.stdout.strip():
            continue

        try:
            matches = json.loads(proc.stdout)
        except json.JSONDecodeError:
            continue

        for m in matches:
            text = m.get("text", "")
            range_info = m.get("range", {})
            start_line = range_info.get("start", {}).get("line", 0) + 1
            end_line = range_info.get("end", {}).get("line", 0) + 1

            symbol_name = _extract_symbol_name(lang, text)
            if symbol_name == "unknown" or len(text.strip()) < 10:
                continue

            signals, direct_calls = _analyze_text_function(lang, symbol_name, text, start_line)
            is_priv = _is_private_symbol(lang, symbol_name, text)

            if is_priv:
                private_defs[symbol_name] = (signals, direct_calls)

            called_private = [
                call
                for call in direct_calls
                if _is_private_symbol(lang, call, "") or call.startswith("_")
            ]

            candidate = CandidateSymbol(
                path=rel_path,
                symbol=symbol_name,
                start_line=start_line,
                end_line=end_line,
                signals=signals,
                direct_private_helpers=sorted(set(called_private)),
            )
            candidates.append(candidate)

            for helper in called_private:
                helper_call_map[helper].add(symbol_name)

    # Post-process Queue C signals
    for cand in candidates:
        single_use = 0
        max_depth = 1 if cand.direct_private_helpers else 0

        for helper in cand.direct_private_helpers:
            callers = helper_call_map.get(helper, set())
            if len(callers) == 1:
                single_use += 1

            if helper in private_defs:
                _, helper_calls = private_defs[helper]
                nested_private = [
                    c for c in helper_calls if _is_private_symbol(lang, c, "") or c.startswith("_")
                ]
                if nested_private and max_depth < 2:
                    max_depth = 2

        cand.signals.single_use_private_helper_count = single_use
        cand.signals.private_call_depth = max_depth
        cand.signals.private_helper_fanout = len(cand.direct_private_helpers)

    return candidates


def rank_and_select(
    candidates: list[CandidateSymbol], top_k_per_queue: int = 2
) -> tuple[list[CandidateSymbol], dict[str, list[CandidateSymbol]]]:
    """Ranks candidates across the 3 queues and selects top candidates."""
    q_control = [
        c for c in candidates if c.signals.decision_count >= 3 or c.signals.max_nesting >= 2
    ]
    q_mutation = [
        c for c in candidates if c.signals.mutation_sites >= 2 and c.signals.mutation_span >= 5
    ]
    q_navigation = [
        c
        for c in candidates
        if c.signals.single_use_private_helper_count >= 1 or c.signals.private_helper_fanout >= 2
    ]

    q_control.sort(key=lambda c: c.control_score, reverse=True)
    q_mutation.sort(key=lambda c: c.mutation_score, reverse=True)
    q_navigation.sort(key=lambda c: c.navigation_score, reverse=True)

    top_control = q_control[:top_k_per_queue]
    top_mutation = q_mutation[:top_k_per_queue]
    top_navigation = q_navigation[:top_k_per_queue]

    selected_dict: dict[tuple[str, str], CandidateSymbol] = {}

    for c in top_control:
        key = (c.path, c.symbol)
        if key not in selected_dict:
            selected_dict[key] = c
        if "control" not in selected_dict[key].candidate_queues:
            selected_dict[key].candidate_queues.append("control")

    for c in top_mutation:
        key = (c.path, c.symbol)
        if key not in selected_dict:
            selected_dict[key] = c
        if "mutation" not in selected_dict[key].candidate_queues:
            selected_dict[key].candidate_queues.append("mutation")

    for c in top_navigation:
        key = (c.path, c.symbol)
        if key not in selected_dict:
            selected_dict[key] = c
        if "navigation" not in selected_dict[key].candidate_queues:
            selected_dict[key].candidate_queues.append("navigation")

    for cand in selected_dict.values():
        scores = {
            "control": cand.control_score,
            "mutation": cand.mutation_score,
            "navigation": cand.navigation_score,
        }
        cand.primary_queue = max(cand.candidate_queues, key=lambda q: scores.get(q, 0))

    final_roster = list(selected_dict.values())
    queue_rosters = {
        "control": top_control,
        "mutation": top_mutation,
        "navigation": top_navigation,
    }
    return final_roster, queue_rosters


def main() -> int:
    _force_utf8_stdout()
    parser = argparse.ArgumentParser(
        description="audit_hotspots.py — implementation-hotspot candidate scanner."
    )
    parser.add_argument(
        "repo_root",
        nargs="?",
        default=".",
        help="Target repository root directory (default: current directory)",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=2,
        help="Top candidates per queue to select (default: 2, max deduplicated: 6)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit structured JSON with promotion_allowed: false",
    )
    args = parser.parse_args()

    repo_dir = Path(args.repo_root).resolve()
    if not repo_dir.is_dir():
        sys.stderr.write(f"error: '{repo_dir}' is not a directory\n")
        return 2

    # Discover source files
    py_files: list[Path] = []
    non_py_files: list[tuple[Path, str]] = []

    for p in sorted(repo_dir.rglob("*")):
        if not p.is_file():
            continue
        if any(part in IGNORE_DIRS for part in p.parts):
            continue
        if _is_test_file(p.name) or _is_generated_file(p):
            continue

        ext = p.suffix.lower()
        if ext == ".py":
            py_files.append(p)
        elif ext in _LANG_BY_EXT:
            non_py_files.append((p, _LANG_BY_EXT[ext]))

    ast_grep_bin = shutil.which("ast-grep") or shutil.which("sg")
    ast_grep_missing = non_py_files and not ast_grep_bin

    if not py_files and not non_py_files:
        if args.json:
            sys.stdout.write(
                json.dumps(
                    {
                        "schema_version": 1,
                        "status": "clean",
                        "promotion_allowed": False,
                        "candidates": [],
                        "queue_counts": {"control": 0, "mutation": 0, "navigation": 0},
                    },
                    indent=2,
                )
                + "\n"
            )
        else:
            sys.stderr.write("audit_hotspots: no supported source files identified.\n")
        return 0

    if not py_files and ast_grep_missing:
        # Only non-Python files exist, and ast-grep is absent: skip gracefully with install guidance
        if args.json:
            sys.stdout.write(
                json.dumps(
                    {
                        "schema_version": 1,
                        "status": "absent",
                        "tool": "ast-grep",
                        "install_instructions": INSTALL_INSTRUCTIONS,
                        "message": (
                            f"ast-grep not found on PATH. Multi-language scanning skipped for "
                            f"{len(non_py_files)} non-Python file(s)."
                        ),
                        "doctrine": (
                            "Candidate evidence for Critic Method Step 6 (promotion_allowed: false). "
                            "Metrics support judgment; they never decide it."
                        ),
                        "promotion_allowed": False,
                        "candidates": [],
                        "queue_counts": {"control": 0, "mutation": 0, "navigation": 0},
                    },
                    indent=2,
                )
                + "\n"
            )
        else:
            sys.stderr.write(
                f"audit_hotspots: 'ast-grep' not found on PATH. Multi-language scanning skipped for "
                f"{len(non_py_files)} file(s).\n"
                f"To install ast-grep: {INSTALL_INSTRUCTIONS}\n"
            )
        return 0

    # Collect candidates
    candidates: list[CandidateSymbol] = []
    for p in py_files:
        candidates.extend(scan_python_file(p, repo_dir))

    if not ast_grep_missing:
        for p, lang in non_py_files:
            candidates.extend(scan_non_python_file(p, lang, repo_dir))
    elif non_py_files:
        sys.stderr.write(
            f"audit_hotspots: 'ast-grep' not found on PATH. Skipped {len(non_py_files)} non-Python file(s). "
            f"To install: {INSTALL_INSTRUCTIONS}\n"
        )

    roster, queue_rosters = rank_and_select(candidates, top_k_per_queue=args.top_k)

    if args.json:
        doc = {
            "schema_version": 1,
            "doctrine": (
                "Candidate evidence for Critic Method Step 6 (promotion_allowed: false). "
                "Metrics support judgment; they never decide it. The Critic independently "
                "validates candidate symbols against source."
            ),
            "promotion_allowed": False,
            "candidates": [
                {
                    "path": c.path,
                    "symbol": c.symbol,
                    "line_range": {"start": c.start_line, "end": c.end_line},
                    "candidate_queues": c.candidate_queues,
                    "primary_queue": c.primary_queue,
                    "signals": asdict(c.signals),
                    "neighborhood": {"direct_private_helpers": c.direct_private_helpers},
                }
                for c in roster
            ],
            "queue_counts": {
                "control": len(queue_rosters["control"]),
                "mutation": len(queue_rosters["mutation"]),
                "navigation": len(queue_rosters["navigation"]),
            },
        }
        if ast_grep_missing:
            doc["tool_notice"] = {
                "tool": "ast-grep",
                "status": "absent",
                "install_instructions": INSTALL_INSTRUCTIONS,
            }
        sys.stdout.write(json.dumps(doc, indent=2) + "\n")
        return 0

    if not roster:
        sys.stderr.write("audit_hotspots: no implementation hotspots identified.\n")
        return 0

    print("### Implementation Hotspot Candidates (`promotion_allowed: false`)")
    print(
        "*Advisory candidate evidence for Critic Method Step 6.* "
        "*Run 3-way triage (confirm | contextualize | dismiss) against source semantics before forming findings.*\n"
    )
    print("| Symbol | File:Lines | Queues | Key Signals | Direct Helpers |")
    print("|---|---|---|---|---|")
    for c in roster:
        queues_str = ", ".join(c.candidate_queues)
        sig = c.signals
        key_sigs = (
            f"decisions={sig.decision_count}, nesting={sig.max_nesting}, "
            f"mut_span={sig.mutation_span}, single_helpers={sig.single_use_private_helper_count}"
        )
        helpers_str = ", ".join(c.direct_private_helpers) if c.direct_private_helpers else "none"
        print(
            f"| `{c.symbol}` | `{c.path}:{c.start_line}-{c.end_line}` | {queues_str} | {key_sigs} | {helpers_str} |"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
