#!/usr/bin/env python3
"""audit_boundaries.py — flag circular first-party import dependencies.

Usage: scripts/audit_boundaries.py [<repo-root>]
Default: cwd.

Mechanical helper for Method Step 3 (Review architecture — module graph / Seams).
A circular import between first-party top-level packages is a coupling smell: the
two packages cannot be understood, tested, or deleted independently, which is a
leaky-Seam signal. Output is **advisory evidence for the Critic** — a candidate
finding, never a hard gate and never an auto-score. The loop does not block on it.

Why Python + `ast` (not Bash regex): the sibling `audit-*.sh` helpers grep
*metadata* (churn counts, name clusters). This one parses *source structure*, where
a line-regex would mis-handle multi-line imports, aliases, and `import` strings
inside comments/string literals — producing false cycles that would poison the
Critic's signal. `ast` parses the real import graph, so those classes never trip it.

Supported stacks: **Python only (v1)**. Unsupported stacks emit nothing and exit 0
(a Swift extension would shell to `ast-grep`/`sg`, guarded by `shutil.which`, and
degrade to silent if the binary is absent — not implemented in v1). This keeps the
single-language scope honest rather than faking breadth.

Output: markdown table to stdout, one row per circular-dependency group. When clean
(or unsupported/empty), nothing is printed to stdout and a note goes to stderr.

Exit codes: 0 = ran (clean, with-findings, or unsupported-empty — advisory, never a
loop gate); 2 = usage error (bad path). The exit code is for tooling/self-tests; the
loop reads the *stdout findings*, not the exit code.

Run: python3 scripts/audit_boundaries.py [<repo-root>]
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

# Directory names never scanned: VCS/build/cache/vendor + test + generated trees.
# `tests`/`test` are excluded so a back-edge that lives only in a test file does not
# manufacture a production cycle (a documented restraint).
IGNORE_DIRS = frozenset(
    {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        ".env",
        "build",
        "dist",
        ".tox",
        ".mypy_cache",
        ".pytest_cache",
        "site-packages",
        "migrations",
        "tests",
        "test",
        ".eggs",
    }
)

# Generated / test file basenames: skipped so generated back-edges and test-only
# imports do not create production cycles.
_GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "Generated by")


def _is_test_file(name: str) -> bool:
    return name.startswith("test_") or name.endswith("_test.py")


def _is_generated_file(path: Path) -> bool:
    if path.name.endswith(("_pb2.py", "_pb2_grpc.py")):
        return True
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:400]
    except OSError:
        return False
    return any(marker in head for marker in _GENERATED_MARKERS)


def _collect_py_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*.py"):
        rel_parts = path.relative_to(root).parts
        if any(part in IGNORE_DIRS for part in rel_parts[:-1]):
            continue
        if _is_test_file(path.name) or _is_generated_file(path):
            continue
        files.append(path)
    return files


def _source_root(root: Path) -> Path:
    # `src/` layout is common; if present, packages live under it.
    src = root / "src"
    return src if src.is_dir() else root


def _package_of(path: Path, source_root: Path) -> str:
    rel = path.relative_to(source_root)
    # nested file → first path component is the top-level package;
    # top-level file → its own module stem acts as a package.
    return rel.parts[0] if len(rel.parts) > 1 else path.stem


def _imported_top_levels(tree: ast.AST) -> set[str]:
    tops: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:  # `import a.b as c` → top-level is `a`
                tops.add(alias.name.split(".", 1)[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level:  # relative import (`from . import x`) — intra-package
                continue
            if node.module:  # `from a.b import x` → top-level is `a`
                tops.add(node.module.split(".", 1)[0])
    return tops


def _build_graph(files: list[Path], source_root: Path) -> dict[str, set[str]]:
    first_party = {_package_of(f, source_root) for f in files}
    graph: dict[str, set[str]] = {pkg: set() for pkg in first_party}
    for f in files:
        pkg = _package_of(f, source_root)
        try:
            tree = ast.parse(f.read_text(encoding="utf-8", errors="replace"), filename=str(f))
        except (SyntaxError, ValueError):
            continue  # unparseable file → skip; never crash the audit
        for top in _imported_top_levels(tree):
            if top in first_party and top != pkg:  # cross-package, first-party only
                graph[pkg].add(top)
    return graph


def _strongly_connected_components(graph: dict[str, set[str]]) -> list[list[str]]:
    """Tarjan's SCC (iterative — no recursion-limit risk). Deterministic order."""
    index_of: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    sccs: list[list[str]] = []
    counter = 0

    for start in sorted(graph):
        if start in index_of:
            continue
        work: list[tuple[str, int]] = [(start, 0)]
        while work:
            node, child_i = work[-1]
            if child_i == 0:
                index_of[node] = low[node] = counter
                counter += 1
                stack.append(node)
                on_stack.add(node)
            successors = sorted(graph[node])
            if child_i < len(successors):
                work[-1] = (node, child_i + 1)
                nxt = successors[child_i]
                if nxt not in index_of:
                    work.append((nxt, 0))
                elif nxt in on_stack:
                    low[node] = min(low[node], index_of[nxt])
            else:
                if low[node] == index_of[node]:
                    comp: list[str] = []
                    while True:
                        w = stack.pop()
                        on_stack.discard(w)
                        comp.append(w)
                        if w == node:
                            break
                    sccs.append(sorted(comp))
                work.pop()
                if work:
                    parent = work[-1][0]
                    low[parent] = min(low[parent], low[node])
    return sccs


def _cycles(graph: dict[str, set[str]]) -> list[list[str]]:
    cycles: list[list[str]] = []
    for comp in _strongly_connected_components(graph):
        # multi-package SCC, or a rare single-package self-cycle
        if len(comp) > 1 or (len(comp) == 1 and comp[0] in graph[comp[0]]):
            cycles.append(comp)
    return sorted(cycles, key=lambda c: (len(c), c))


def main(argv: list[str]) -> int:
    root = Path(argv[1]).resolve() if len(argv) > 1 else Path.cwd()
    if not root.is_dir():
        print(f"audit-boundaries: not a directory: {root}", file=sys.stderr)
        return 2

    source_root = _source_root(root)
    files = _collect_py_files(source_root)
    if not files:
        print(
            "audit-boundaries: no first-party Python sources found "
            "(Python-only v1; unsupported stacks emit nothing)",
            file=sys.stderr,
        )
        return 0

    cycles = _cycles(_build_graph(files, source_root))
    if not cycles:
        print("audit-boundaries: no first-party import cycles found", file=sys.stderr)
        return 0

    print("| candidate finding | packages in cycle | size |")
    print("|---|---|---|")
    for comp in cycles:
        chain = " ↔ ".join(comp)
        print(f"| circular import dependency | {chain} | {len(comp)} |")
    print(
        f"\n{len(cycles)} circular-import group(s) — advisory evidence for the Critic "
        "(leaky-Seam signal); not a finding by itself and not a loop gate.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
